image: docker:latest
services:
- docker:dind
variables:
  DOCKER_DRIVER: overlay

pages:
  image: node:10-alpine
  stage: deploy
  only:
  - pages
  script:
  - cd app
  - npm install
  - npm run build:prod:libs
  - npm run build:prod:client
  - mv dist/portal-browser/ public/